sudo: required

language: python

services:
  - docker

env:
  global:
  - IMAGE_VERSION=0.0.1

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/cryptocurrency_exporter .
      - docker images
      - docker push $DOCKER_USERNAME/cryptocurrency_exporter
      - docker tag $DOCKER_USERNAME/cryptocurrency_exporter $DOCKER_USERNAME/cryptocurrency_exporter:${IMAGE_VERSION}
      - docker push $DOCKER_USERNAME/cryptocurrency_exporter:${IMAGE_VERSION}
    - stage: test
      script: 
      - docker run --rm -p 0.0.0.0:9510:9510 $DOCKER_USERNAME/cryptocurrency_exporter --test
    - stage: secondtest
      script:
      - docker run -d -p 0.0.0.0:9510:9510 $DOCKER_USERNAME/cryptocurrency_exporter --test
      - for i in {1..30}; do curl localhost:9150; done
